server:
  port: 8085

spring:
  h2:
    console:
      enabled: true #웹 콘솔
      path: /h2-console #콘솔 경로

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    generate-unique-name: false #jdbc url 랜덤 생성
#    username: kokoo
#    password: kokoo

  jpa:
    show-sql: true
    properties:
      hibernamte:
        format_sql: true